version: "3"
services: 
  web:
    image: benedictaquino/website:latest
    deploy:
      replicas: 5
     #resources:
     #  limits:
     #    cpus: "0.2"
     #    memory: 1G
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
